POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "fullstack",
  "email": "fullstack@gmail.com",
  "password": "Fullstack2021"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "Admin2021"
}

###

GET http://localhost:3000/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBcGlBdXRoIiwic3ViIjoiNjAzNzhjZWExNmJkOWE1OTA0M2VmMDE3IiwiaWF0IjoxNjE1NDgzODQ0NTI3LCJleHAiOjE2MTU1NzAyNDQ1Mjd9.tlcSGmDD0jTB2SHbUQ4dPyTRUY5FIJPHtTcZEpecGGc

###

GET http://localhost:3000/orders/60378cea16bd9a59043ef017
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBcGlBdXRoIiwic3ViIjoiNjAzNzhjZWExNmJkOWE1OTA0M2VmMDE3IiwiaWF0IjoxNjE2MzIzNTc0ODcwLCJleHAiOjE2MTY0MDk5NzQ4NzB9.ksaoaNW-PstBmt1KZDLATji_DhYLOiXNk6MnEsEhbj4

###

POST  http://localhost:3000/orders/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBcGlBdXRoIiwic3ViIjoiNjAzNzhjZWExNmJkOWE1OTA0M2VmMDE3IiwiaWF0IjoxNjE1NDgzODQ0NTI3LCJleHAiOjE2MTU1NzAyNDQ1Mjd9.tlcSGmDD0jTB2SHbUQ4dPyTRUY5FIJPHtTcZEpecGGc
Content-Type: application/json

{
  "userId": "604bd2c072ee191554febea4"
}

###

GET http://localhost:3000/auth/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBcGlBdXRoIiwic3ViIjoiNjAzNGFhNTc2ZjMxZTM3NzFjNWEzNzRiIiwiaWF0IjoxNjE0MjQ1NTIxNzI0LCJleHAiOjE2MTQzMzE5MjE3MjR9.1NXY3jIPLW3bnB6F_IaHnpKvCiMlPZ76IAK73St1YUM

###

GET http://localhost:3000/auth/validate_token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBcGlBdXRoIiwic3ViIjoiNjAzNzhjZWExNmJkOWE1OTA0M2VmMDE3IiwiaWF0IjoxNjE2NTk2NDg2MDA3LCJleHAiOjE2MTY2ODI4ODYwMDd9.CkRSMlAkU1c2oO8SX99XbF2qoYBTwvzuaavz6Nb_NPw
###

GET http://localhost:3000/auth/check_role
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBcGlBdXRoIiwic3ViIjoiNjA0ZTM2Y2FkNTI5YzQ2OWIwOWMxYTJlIiwiaWF0IjoxNjE2NzgwMzgzMDkxLCJleHAiOjE2MTY4NjY3ODMwOTF9.0AROZV6Hk-iFgwKtkbi4I0faOWliZ6OmXpPtpAIUSp0
###

GET http://localhost:3000/films/
Content-Type: application/json

###

POST http://localhost:3000/films/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBcGlBdXRoIiwic3ViIjoiNjA0ZTM2Y2FkNTI5YzQ2OWIwOWMxYTJlIiwiaWF0IjoxNjE2NDM1MjA4MzQ1LCJleHAiOjE2MTY1MjE2MDgzNDV9.xWTfAseu0k0nAhoJ0XkYjX_1XAFWOVtTtY0WPyI7Ux8
Content-Type: application/json

  {
    "id": 3,
    "title": "Небеса подождут",
    "genres": ["мелодрама", "комедия", "драма"],
    "description": "Штеффи всего 16, её жизнь только начинается: первая любовь, выпускной, поездка с классом в Париж. Но после неожиданного вердикта врачей всё это придется отменить: Штеффи ждет серьезное лечение в больнице.",
    "age": 16,
    "imageSrc": "https://www.film.ru/sites/default/files/movies/posters/49630424-1373506.jpg",
    "duration": {
      "hours": 3,
      "minutes": 0
    },
    "startDate": 1612645200,
    "endDate": 1614459600
  }

###

GET http://localhost:3000/cinemas/
Content-Type: application/json

###

POST http://localhost:3000/cinemas/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBcGlBdXRoIiwic3ViIjoiNjA0ZTM2Y2FkNTI5YzQ2OWIwOWMxYTJlIiwiaWF0IjoxNjE2NDM1MjA4MzQ1LCJleHAiOjE2MTY1MjE2MDgzNDV9.xWTfAseu0k0nAhoJ0XkYjX_1XAFWOVtTtY0WPyI7Ux8
Content-Type: application/json

  {
    "name": "Кинотеатр 3",
    "city": "Витебск",
    "address": "ул. Ленина, 35",
    "halls": [
      {
        "seatsTypes": ["Standard", "Love Seats"],
        "plan": [
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Love Seats", "Love Seats", "Love Seats", "Love Seats", "Love Seats", "Love Seats", "Love Seats"]
        ]
      },
      {
        "seatsTypes": ["Standard", "VIP"],
        "plan": [
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard"],
          ["VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP"]
        ]
      },
      {
        "seatsTypes": ["Standard", "VIP"],
        "plan": [
          ["VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard"],
          ["Standard", "Standard", "Standard","Standard","Standard","Standard","Standard","Standard", "Standard", "Standard", "Standard","Standard","Standard","Standard"]
        ]
      }
    ],
    "additionalServices": [
      {
        "name": "Попкорн",
        "price": 4,
        "quantity": "200г"
      }
    ]
  }

###

POST http://localhost:3000/seances/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBcGlBdXRoIiwic3ViIjoiNjA0ZTM2Y2FkNTI5YzQ2OWIwOWMxYTJlIiwiaWF0IjoxNjE2NDM1MjA4MzQ1LCJleHAiOjE2MTY1MjE2MDgzNDV9.xWTfAseu0k0nAhoJ0XkYjX_1XAFWOVtTtY0WPyI7Ux8
Content-Type: application/json

      {
        "film": "603b6b323997e274e40be10f",
        "startTime": 1615741200,
        "endTime": 1615752000,
        "cinema": "603bf46b856b4731047abdc4",
        "hallNumber": 1,
        "format": "2D",
        "occupiedSeats": [
          [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
          [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
          [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
          [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
          [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
          [false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false],
          [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false],
          [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
          [false, false, false, false, false, true, true, true, false, false, false, false, false, false, false, false],
          [false, false, true, true, true, false, false]
        ],
        "prices": {
          "Standard": 8,
          "Love Seats": 20
        }
      }

###

POST http://localhost:3000/services/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBcGlBdXRoIiwic3ViIjoiNjA0ZTM2Y2FkNTI5YzQ2OWIwOWMxYTJlIiwiaWF0IjoxNjE2NDM1MjA4MzQ1LCJleHAiOjE2MTY1MjE2MDgzNDV9.xWTfAseu0k0nAhoJ0XkYjX_1XAFWOVtTtY0WPyI7Ux8
Content-Type: application/json
          
{
  "name": "Попкорн1",
  "price": 4,
  "quantity": "200г"
}

